linuxdeepin/dde-api-proxy

src/dbus-proxy/CMakeLists.txt, src/dbus-proxy/common/dbusproxybase.hpp
Log: handle when log is too much
resolve: https://github.com/linuxdeepin/developer-center/issues/3934
=> fix: handle when log is too much

.obs/workflows.yml
=> chore: add OBS workflows

debian/changelog
=> chore: create new tag

src/dbus-proxy/common/dbusproxybase.hpp
=> fix: 修复 GetAll 崩溃

file/dbus/v1/session/org.deepin.dde.Appearance1.xml
=> chore: update appearance dbus xml

src/dbus-proxy/v1/session/org_deepin_dde_ShutdownFront1.hpp
=> chore: 开放ShutdownFront接口权限

debian/control, file/dbus/v1/session/org.deepin.dde.Display1.xml
=> chore: 去掉dde-dock依赖

file/dbus/v1/session/org.deepin.dde.Power1.xml, src/dbus-proxy/v1/session/org_deepin_dde_Power1.hpp
=> chore: 开放power接口

file/dbus/v1/system/org.deepin.dde.Power1.xml, src/dbus-proxy/v1/system/org_deepin_dde_Power1.hpp
=> chore: 开放system/power的接口

src/dbus-proxy/v1/session/org_deepin_dde_LockFront1.hpp
=> chore: 开放lockfront的接口

file/dbus/v0/session/com.deepin.dde.Notification.xml, file/dbus/v1/session/org.deepin.dde.Notification1.xml, src/dbus-proxy/v1/session/org_deepin_dde_Notification1.hpp
开放Notification V0接口
Issue: https://github.com/linuxdeepin/developer-center/issues/9687
=> chore: 开放Notification V0接口

file/dbus/v0/session/com.deepin.daemon.Display.xml, file/dbus/v0/session/com.deepin.daemon.Network.xml, file/dbus/v1/session/org.deepin.dde.Network1.xml, src/dbus-proxy/v1/session/org_deepin_dde_Network1.hpp, src/dbus-proxy/v1/session/org_deepin_dde_Timedate1.hpp
=> chore: 开放显示/网络/时间的V0接口权限，适配任务栏插件

src/dbus-proxy/v1/system/org_deepin_dde_Network1.hpp
=> chore: 开放system/network权限

file/dbus/v0/session/com.deepin.daemon.Audio.xml, file/dbus/v1/session/org.deepin.dde.Audio1.xml, src/dbus-proxy/common/dbusproxybase.hpp
=> chore: 解决属性change信号转发的问题

debian/changelog
release to 1.0.13
Log: release to 1.0.13
=> chore: release to 1.0.13

debian/changelog
=> chore: release to 1.0.14

src/dbus-proxy/common/dbusproxybase.hpp
=> chore: 属性是subPath，发送的信号也需要转换

src/dbus-proxy/v1/system/org_deepin_dde_Accounts1.hpp, src/dbus-proxy/v1/system/org_deepin_dde_Accounts1_User.hpp
=> chore: 放开account的接口

debian/changelog
=> chore: release to 1.0.15

debian/changelog
=> chore: release to 1.0.16

file/dbus/v0/system/com.deepin.daemon.Accounts.User.xml, file/dbus/v1/system/org.deepin.dde.Accounts1.User.xml
account添加UUID、Workspace属性，解决获取不到的问题
=> chore: account添加UUID、Workspace属性，解决获取不到的问题

debian/changelog
=> chore: release to 1.0.17

misc/systemd/system/dde-api-dbus-proxy-v1@.service
加固 dbus 进程
Task: https://pms.uniontech.com/task-view-361201.html
=> chore: systemd hardening

debian/control
添加polkit的编译依赖
Log: 添加polkit的编译依赖
pms: task-371895
=> fix: 添加polkit的编译依赖

src/dbus-proxy/common/dbusproxybase.hpp
根据CVE-2013-4288,采用SystemBusNameSubject
Log: 修复dde-api-proxy安全漏洞
pms: task-372233
=> feat: 修复dde-api-proxy安全漏洞

debian/changelog
=> chore: Bump version to 1.0.20
